import test from 'node:test';import assert from 'node:assert/strict';
import {optimizeCutting,validateCuttingInput} from '../src/cuttingOptimizer.js';
import {saveCuttingPlan,loadCuttingPlan,saveCuttingOffcut,readCuttingStore,saveCuttingDraft,removeCuttingOffcut} from '../src/cuttingStorage.js';
const stock=(patch={})=>({id:'stock',name:'Sheet',material:'MDF',thickness:18,length:2440,width:1220,quantity:5,grain:'Any',...patch});
const part=(patch={})=>({id:'part',name:'Side',material:'MDF',thickness:18,length:700,width:450,quantity:2,grain:'Any',rotate:true,...patch});
const input=(patch={})=>({stocks:[stock()],parts:[part()],kerf:3,trim:0,...patch});
function verify(result){for(const sheet of result.sheets){const ps=sheet.placements;for(const p of ps){assert.ok(p.x>=result.input.trim-1e-6&&p.y>=result.input.trim-1e-6);assert.ok(p.x+p.w<=sheet.length-result.input.trim+1e-6);assert.ok(p.y+p.h<=sheet.width-result.input.trim+1e-6);for(const q of ps)if(p!==q){const separated=p.x+p.w<=q.x+1e-6||q.x+q.w<=p.x+1e-6||p.y+p.h<=q.y+1e-6||q.y+q.h<=p.y+1e-6;assert.ok(separated,'parts overlap')}}
 let loss=0;for(const cut of sheet.cuts){assert.ok(cut.distance>=0);assert.ok(cut.axis==='vertical'?cut.distance+result.input.kerf<=cut.region.w+1e-6:cut.distance+result.input.kerf<=cut.region.h+1e-6);loss+=cut.span*result.input.kerf}const used=ps.reduce((a,p)=>a+p.w*p.h,0),free=sheet.free.reduce((a,r)=>a+r.w*r.h,0);assert.ok(Math.abs(used+free+loss+(sheet.trimWasteArea||0)-sheet.length*sheet.width)<1e-4,'area conservation');}}
test('single sheet, quantity expansion and realistic example have valid no-overlap geometry',()=>{const r=optimizeCutting(input({parts:[part(),part({id:'shelf',name:'Shelf',length:650,width:400,quantity:4}),part({id:'door',length:700,width:300,quantity:2,grain:'Vertical',rotate:false})]}));assert.equal(r.summary.placed,8);assert.equal(r.unplaced.length,0);verify(r);assert.equal(new Set(r.sheets.flatMap(s=>s.placements.map(p=>p.instanceId))).size,8)});
test('multiple sheets and stock exhaustion are real',()=>{const r=optimizeCutting(input({stocks:[stock({length:1000,width:1000,quantity:2})],parts:[part({length:900,width:900,quantity:3})]}));assert.equal(r.summary.sheets,2);assert.equal(r.summary.placed,2);assert.equal(r.unplaced.length,1);verify(r)});
test('kerf separates parts: 610+610 fits 1220 only at zero kerf',()=>{const raw=input({stocks:[stock({length:1220,width:1000,quantity:1})],parts:[part({length:610,width:1000,quantity:2,rotate:false})],kerf:0});assert.equal(optimizeCutting(raw).summary.placed,2);const r=optimizeCutting({...raw,kerf:3});assert.equal(r.summary.placed,1);verify(r)});
test('kerf is charged only for actual split boundaries, exact edge fit needs no cut',()=>{const r=optimizeCutting(input({stocks:[stock({length:700,width:450,quantity:1})],parts:[part({quantity:1})]}));assert.equal(r.cuts.length,0);assert.equal(r.summary.wasteArea,0);verify(r)});
test('grain locked and directional parts cannot rotate; Any may rotate when allowed',()=>{const raw=input({stocks:[stock({length:400,width:700,quantity:1})],parts:[part({length:700,width:400,quantity:1})]});assert.equal(optimizeCutting(raw).summary.placed,1);assert.equal(optimizeCutting(raw).sheets[0].placements[0].rotated,true);for(const grain of ['Locked','Vertical','Horizontal'])assert.equal(optimizeCutting({...raw,parts:[part({length:700,width:400,quantity:1,grain})]}).summary.placed,0);assert.equal(optimizeCutting({...raw,parts:[part({length:700,width:400,quantity:1,rotate:false})]}).summary.placed,0)});
test('direction must match declared stock grain, dimensions and thickness match material',()=>{const r=optimizeCutting(input({stocks:[stock({grain:'Horizontal'})],parts:[part({grain:'Vertical'}),part({id:'wrong',thickness:12})]}));assert.equal(r.summary.placed,0);assert.match(r.unplaced[2].reason,/Thickness/)});
test('existing matching offcuts are preferred to new sheets and incompatible offcuts skipped',()=>{const r=optimizeCutting(input({stocks:[stock(),stock({id:'off',length:850,width:500,quantity:1,offcut:true})],parts:[part({quantity:1})]}));assert.equal(r.summary.newSheets,0);assert.equal(r.summary.offcutStock,1);assert.equal(r.sheets[0].stockId,'off');verify(r)});
test('oversize parts are reported, not silently dropped',()=>{const r=optimizeCutting(input({parts:[part({length:9000,width:9000,quantity:1})]}));assert.equal(r.unplaced.length,1);assert.match(r.unplaced[0].reason,/larger/)});
test('edge trim removes material on all sides and produces physical boundary cuts',()=>{const r=optimizeCutting(input({trim:10}));verify(r);assert.equal(r.sheets[0].cuts.filter(c=>c.trim).length,4);const tight=optimizeCutting(input({stocks:[stock({length:700,width:450})],trim:10,parts:[part({quantity:1})]}));assert.equal(tight.summary.placed,0)});
test('used and unused area percentages account for real geometry including reusable area',()=>{const r=optimizeCutting(input());verify(r);const s=r.summary;assert.equal(s.usedArea,700*450*2);assert.equal(s.totalArea,2440*1220);assert.equal(s.wasteArea,s.totalArea-s.usedArea);assert.ok(Math.abs(s.usedPercent+s.wastePercent-100)<1e-8);assert.equal(s.discardArea+s.reusableArea,s.wasteArea)});
test('reject invalid numbers, quantities, material, grain and destructive trim',()=>{for(const patch of [{kerf:-1},{kerf:'x'},{trim:2},{trim:10000},{parts:[part({length:0})]},{parts:[part({width:-2})]},{parts:[part({quantity:0})]},{parts:[part({quantity:1.5})]},{parts:[part({material:''})]},{parts:[part({grain:'diagonal'})]},{parts:[part({thickness:0})]},{parts:[part({quantity:201})]}])assert.throws(()=>validateCuttingInput(input(patch)))});
test('deterministic results and immutable inputs',()=>{const raw=input(),before=JSON.stringify(raw);assert.deepEqual(optimizeCutting(raw),optimizeCutting(raw));assert.equal(JSON.stringify(raw),before)});
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}};
test('offline save/load plan and draft, idempotent offcut stock, explicit consume',()=>{const s=memory(),raw=input(),result=optimizeCutting(raw);saveCuttingPlan(s,raw,result,'plan');saveCuttingPlan(s,raw,result,'plan');assert.equal(readCuttingStore(s).plans.length,1);assert.deepEqual(loadCuttingPlan(s,'plan').result,result);saveCuttingDraft(s,raw);assert.deepEqual(readCuttingStore(s).draft,raw);const o=result.offcuts[0];assert.ok(o);assert.equal(saveCuttingOffcut(s,o,'plan'),true);assert.equal(saveCuttingOffcut(s,o,'plan'),false);assert.equal(readCuttingStore(s).offcuts.length,1);removeCuttingOffcut(s,'plan:'+o.id);assert.equal(readCuttingStore(s).offcuts.length,0)});
test('unreadable/quota local storage never claims success or overwrites data',()=>{assert.throws(()=>saveCuttingPlan({getItem:()=>'{bad',setItem:()=>assert.fail('overwrite')},input(),{},'p'));assert.throws(()=>saveCuttingDraft({getItem:()=>null,setItem(){throw Error('quota')}},input()),/Could not save/)});
test('100-part plan remains responsive with genuine geometry',()=>{const start=performance.now(),r=optimizeCutting(input({parts:[part({length:150,width:90,quantity:100})]}));assert.equal(r.summary.placed,100);verify(r);assert.ok(performance.now()-start<2000)});
test('many varied deterministic plans conserve area and never overlap',()=>{for(let k=0;k<15;k++){const r=optimizeCutting(input({kerf:k%5,trim:k%5?10:0,parts:Array.from({length:8},(_,i)=>part({id:'p'+i,length:100+(k*79+i*121)%900,width:80+(k*41+i*97)%500,quantity:2,grain:i%3?'Any':'Locked'}))}));verify(r)}});
test('cut sequence splits only an available rectangle and blades do not cross finished parts',()=>{const r=optimizeCutting(input({parts:[part(),part({id:'s',length:650,width:400,quantity:4})]}));for(const s of r.sheets){let regions=[{x:0,y:0,w:s.length,h:s.width}];for(const c of s.cuts){const i=regions.findIndex(q=>['x','y','w','h'].every(k=>Math.abs(q[k]-c.region[k])<1e-7));assert.ok(i>=0,'cut refers to a section not available');const q=regions.splice(i,1)[0];if(c.axis==='vertical'){regions.push({x:q.x,y:q.y,w:c.distance,h:q.h});if(q.w-c.distance-r.input.kerf>0)regions.push({x:q.x+c.distance+r.input.kerf,y:q.y,w:q.w-c.distance-r.input.kerf,h:q.h})}else{regions.push({x:q.x,y:q.y,w:q.w,h:c.distance});if(q.h-c.distance-r.input.kerf>0)regions.push({x:q.x,y:q.y+c.distance+r.input.kerf,w:q.w,h:q.h-c.distance-r.input.kerf})}}for(const p of s.placements)assert.ok(regions.some(q=>['x','y','w','h'].every(k=>Math.abs(q[k]-p[k])<1e-7)),'finished part not isolated by sequence')}});
test('exact blade-sized remainder is removed and sub-kerf tail is not incorrectly packed',()=>{const raw=input({stocks:[stock({length:703,width:450,quantity:1})],parts:[part({quantity:1,rotate:false})]});const r=optimizeCutting(raw);assert.equal(r.summary.placed,1);verify(r);assert.equal(r.cuts.length,1);assert.equal(optimizeCutting({...raw,stocks:[stock({length:702,width:450,quantity:1})]}).summary.placed,0)});
test('saved offcut can feed the next offline optimization with matching metadata',()=>{const storage=memory(),r=optimizeCutting(input());saveCuttingOffcut(storage,r.offcuts[0],'p');const off=readCuttingStore(storage).offcuts[0];const next=optimizeCutting(input({stocks:[stock(),off],parts:[part({length:100,width:100,quantity:1})]}));assert.equal(next.summary.newSheets,0);assert.equal(next.sheets[0].stockId,off.id);verify(next)});
