const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright-core');
import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';
const repo=path.resolve(new URL('../',import.meta.url).pathname),dir=process.env.SCREENSHOT_DIR||'/tmp';const server=createServer((req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname.replace(/^\/SAB-TOOLS\//,'');if(!p||p.endsWith('/'))p+='index.html';res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[path.extname(p)]||'text/plain'));res.end(fs.readFileSync(path.join(repo,'dist',p)))}catch{res.statusCode=404;res.end('missing')}});await new Promise(r=>server.listen(4182,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const issues=[];
try{for(const width of [390,320]){const ctx=await browser.newContext({viewport:{width,height:844}}),page=await ctx.newPage();page.on('pageerror',e=>issues.push(e.message));await page.goto('http://127.0.0.1:4182/SAB-TOOLS/');await page.locator('.splash-overlay').waitFor({state:'hidden'});await page.getByRole('button',{name:'Smart cutting optimizer',exact:true}).click();await page.locator('.cutting-tool').waitFor();await page.locator('.cut-editor .cut-fields').first().getByRole('textbox').nth(0).fill('Wardrobe');await page.locator('.cut-editor .cut-fields').first().getByRole('textbox').nth(1).fill('Sample Customer');
const parts=()=>page.locator('.cut-card').filter({has:page.getByText(/^Part \d+$/)});
let card=parts().nth(0);await card.getByLabel('Part name',{exact:true}).fill('Left side');await card.getByLabel('Length (mm)',{exact:true}).fill('700');await card.getByLabel('Width (mm)',{exact:true}).fill('450');await card.getByLabel('Quantity',{exact:true}).fill('2');await card.getByLabel('Grain',{exact:true}).selectOption('Vertical');await card.getByLabel('Allow 90° rotation').uncheck();
for(const [name,L,W,Q]of [['Shelf','650','400','4'],['Door','700','300','2']]){await page.getByRole('button',{name:'+ Add part',exact:true}).click();const c=parts().last();await c.getByLabel('Part name',{exact:true}).fill(name);await c.getByLabel('Length (mm)',{exact:true}).fill(L);await c.getByLabel('Width (mm)',{exact:true}).fill(W);await c.getByLabel('Quantity',{exact:true}).fill(Q)}
await page.screenshot({path:`${dir}/cutting-input-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Optimize cutting',exact:true}).click();await page.locator('.cut-plan').waitFor();const stats=await page.locator('.cut-stats').innerText();if(!stats.includes('Parts placed\n8'))throw Error('Example did not place eight parts');await page.screenshot({path:`${dir}/cutting-plan-${width}.png`,fullPage:true});
await page.getByRole('button',{name:'Save plan',exact:true}).click();await page.getByRole('button',{name:'Workshop mode',exact:true}).click();await page.locator('.workshop').waitFor();await page.screenshot({path:`${dir}/cutting-workshop-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Next',exact:true}).click();if(!await page.locator('.workshop').innerText().then(s=>s.includes('CUT 2')))throw Error('Workshop sequence did not advance');await page.getByRole('button',{name:'‹ Cutting plan',exact:true}).click();
page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Save to stock',exact:true}).first().click();// Verify print DOM in a real browser without submitting to any printer.
await page.emulateMedia({media:'print'});await page.screenshot({path:`${dir}/cutting-print-${width}.png`,fullPage:true});await page.pdf({path:`${dir}/cutting-plan-${width}.pdf`,format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();await page.locator('.cutting-tool').waitFor();if(await parts().nth(0).getByLabel('Part name',{exact:true}).inputValue()!=='Left side')throw Error('Draft did not survive offline reload');await page.getByText(/^Saved plans/).click();await page.locator('.cut-saved').first().click();await page.locator('.cut-plan').waitFor();if(!await page.locator('.cut-stats').innerText().then(s=>s.includes('Parts placed\n8')))throw Error('Saved offline plan did not load');// Saved stock is really consulted on a fresh optimization, not merely listed.
await page.getByRole('button',{name:'Edit cutting list',exact:true}).click();
await page.locator('.cut-card').filter({has:page.getByText(/^Part \d+$/)}).nth(0).getByLabel('Length (mm)',{exact:true}).fill('100');
await page.locator('.cut-card').filter({has:page.getByText(/^Part \d+$/)}).nth(0).getByLabel('Width (mm)',{exact:true}).fill('100');
await page.getByRole('button',{name:'Optimize cutting',exact:true}).click();await page.locator('.cut-plan').waitFor();
if(!await page.locator('.cut-sheet h2').allTextContents().then(ss=>ss.some(s=>s.startsWith('Offcut'))))throw Error('Saved offcut not used automatically');
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error(`Overflow at ${width}px`);await ctx.close();console.log(`PASS ${width}px: example geometry, save, offcut stock, workshop, print, offline reload and saved plan`);}if(issues.length)throw Error(issues.join('\n'));}finally{await browser.close();server.close()}
