import React,{useState} from 'react';
import {woodCalculation} from './woodCalculations';
import './woodCalculators.css';
import RoundWood from './RoundWood';
import {PageHeader,SectionHeader,ToolCard,Card,Button,InputField,FieldGrid,Segmented,ResultCard} from './ui';
const types = {round:{title:'Round wood',art:'logs'},size:{title:'Size wood',art:'planks'},door:{title:'Flush door',art:'door'}};
const image = kind => `${import.meta.env.BASE_URL}icons/wood-${types[kind].art}.svg`;
export function WoodHome({onSelect,onCalculator}) {
 return <section className="wood-home"><PageHeader title="Your tools"/><div className="ui-stack"><div className="ui-stack" style={{gap:'var(--space-2)'}}>{[['Receipt','▤','Timber receipt / CFT & CBM'],['Cutting','▦','Smart cutting optimizer']].map(([id,icon,label])=><ToolCard key={id} className="wood-receipt" onClick={()=>onSelect(id)}><span aria-hidden="true">{icon}</span><b>{label}</b><span aria-hidden="true">→</span></ToolCard>)}</div><div className="wood-grid">{[['round','imperial'],['size','imperial'],['round','metric'],['size','metric'],['door','imperial'],['door','metric']].map(([kind,system])=><ToolCard key={kind+system} className={'wood-card '+system} onClick={()=>onCalculator(kind,system)} aria-label={`${types[kind].title}, ${system==='metric'?'Meter, centimetre':'Foot, Inch'}`}><span className="wood-unit">{system==='metric'?'Meter, c.m.':'Foot, Inch'}</span><span className="wood-dimension" aria-hidden="true">{system==='metric'?'M':'F'}<sup>{kind==='door'?'2':'3'}</sup></span><img src={image(kind)} alt=""/><b>{types[kind].title}</b></ToolCard>)}</div></div><SectionHeader title="Your business"/><div className="wood-business">{[['Saved','Saved receipts'],['Baki','Baki hisab'],['Customers','Customer list'],['Report','Sale report'],['Level','Bubble level']].map(([id,label])=><Button key={id} small onClick={()=>onSelect(id)}>{label}</Button>)}</div></section>;
}
export default function WoodCalculator(props) {
 return props.kind==='round'?<RoundWood userId={props.userId} system={props.initialSystem} onBack={props.onBack}/>:<SingleWoodCalculator {...props}/>;
}
function SingleWoodCalculator({kind,initialSystem,onBack,onReceipt}) {
 const [system,setSystem]=useState(initialSystem),[fields,setFields]=useState({length:'',width:'',thickness:'',girth:'',pieces:'1',rate:''}),[attempted,setAttempted]=useState(false);
 const metric=system==='metric',door=kind==='door',result=woodCalculation(kind,system,fields);
 const unit=door?(metric?'sq m':'sq ft'):(metric?'CBM':'CFT');
 const dimensionUnit=metric?'m':'ft';
 const inputs=kind==='size'?[['length','Length',dimensionUnit],['width','Width',metric?'cm':'in'],['thickness','Thickness',metric?'cm':'in']]:door?[['length','Length',dimensionUnit],['width','Width',dimensionUnit]]:[['length','Length',dimensionUnit],['girth','Girth',metric?'cm':'in']];
 const switchSystem=value=>{if(value===system)return;if(kind==='round'&&value==='imperial'){onReceipt();return;}setSystem(value);setFields({length:'',width:'',thickness:'',girth:'',pieces:'1',rate:''});setAttempted(false)};
 const badge=<>{metric?'M':'F'}<sup>{door?'2':'3'}</sup></>;
 return <section className="wood-calculator"><PageHeader title={types[kind].title} badge={badge} onBack={onBack} backLabel="Your tools"/><Segmented label="Measurement system" value={system} onChange={switchSystem} options={[['imperial','Foot, Inch'],['metric','Meter, c.m.']]}/><div className="wood-diagram"><img src={image(kind)} alt=""/><span>{kind==='size'?'L × W × T':door?'L × W':'Length × (girth ÷ 4)²'}</span></div><Card as="form" className="wood-measure-form" onSubmit={e=>{e.preventDefault();setAttempted(true)}} noValidate><h2>{kind==='size'?'Plank measurements':door?'Door measurements':'Log measurements'}</h2><FieldGrid>{[...inputs,['pieces','Pieces','pcs'],['rate',`Rate per ${unit}`,`₹ / ${unit}`]].map(([key,label,suffix])=><InputField key={key} className={key==='rate'?'ui-span-2':''} label={label} unit={suffix} type="number" inputMode={key==='pieces'?'numeric':'decimal'} min={key==='rate'?0:0.000001} step={key==='pieces'?1:'any'} value={fields[key]} onChange={e=>{setFields({...fields,[key]:e.target.value});setAttempted(false)}} required/>)}</FieldGrid><Button variant="primary" block type="submit" className="wood-calculate" style={{marginTop:'var(--space-4)'}}>Calculate</Button></Card>{attempted&&!result&&<p className="wood-error" role="alert" style={{marginTop:'var(--space-3)'}}>Enter positive measurements, whole pieces and a rate of 0 or more.</p>}<ResultCard aria-live="polite" items={[{label:door?'Total area':'Total volume',value:result?result.quantity.toFixed(3):'0.000',unit},{label:'Total amount',value:result?result.amount.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}):'₹0'}]}/>{kind==='round'&&<p className="ui-hint" style={{textAlign:'center'}}>Quarter-girth method · Girth = circumference</p>}</section>;
}
