import React,{useEffect,useRef,useState} from 'react';
import {accountIdentity} from './accountIdentity';
import {MENU_MAIN,MENU_SUPPORT,APP_VERSION} from './appMenu';
import './appMenu.css';
const icons={home:'M3 11l9-8 9 8 M5 10v11h14V10 M9 21v-7h6v7',help:'M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5 M12 18h.01',save:'M4 3h14l3 3v15H3V3Z M7 3v6h10V3 M7 21v-7h10v7',profile:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M4 21a8 8 0 0 1 16 0',language:'M3 5h12 M9 3v2 M6 5c0 5 3 8 7 10 M12 5c0 5-3 8-8 10 M14 21l4-10 4 10 M16 17h4',manual:'M3 4h6a3 3 0 0 1 3 3v14 M21 4h-6a3 3 0 0 0-3 3 M3 4v16h6a3 3 0 0 1 3 1 3 3 0 0 1 3-1h6V4',share:'M8 8l8-4 M8 16l8 4 M6 8a2 2 0 1 0 0 .01 M18 4a2 2 0 1 0 0 .01 M18 20a2 2 0 1 0 0 .01',star:'M12 3l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',lock:'M6 10h12v11H6Z M8 10V7a4 4 0 0 1 8 0v3',bug:'M8 9h8v8a4 4 0 0 1-8 0Z M9 9V6h6v3 M3 11h5 M16 11h5 M3 16h5 M16 16h5 M5 5l3 4 M19 5l-3 4'};
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icons[name]||icons.home}/></svg>}
export default function AccountMenu({user,onLogout,items=[],activeItem,onSelect}){
 const {name,email}=accountIdentity(user);
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dialog=useRef(null),trigger=useRef(null);
 useEffect(()=>{setOpen(false);setError('')},[user.uid]);
 useEffect(()=>{if(open&&!dialog.current.open)dialog.current.showModal();if(!open&&dialog.current.open)dialog.current.close()},[open]);
 const close=()=>{setOpen(false);trigger.current?.focus()};
 const choose=id=>{onSelect?.(id);close()};
 const signOut=async()=>{setBusy(true);setError('');try{await onLogout();close()}catch{setError('Could not log out. Please try again.')}finally{setBusy(false)}};
 const rows=list=>list.map(([id,label,icon])=><button key={id} className={'drawer-item'+(activeItem===id?' active':'')} aria-current={activeItem===id?'page':undefined} onClick={()=>choose(id)}><Icon name={icon}/><span>{label}</span>{id==='Rate'&&<small>Soon</small>}</button>);
 return <div className="account-menu"><button className="account-trigger" ref={trigger} aria-label={`Account menu for ${name}`} aria-expanded={open} aria-controls="account-drawer" onClick={()=>setOpen(true)}><svg className="account-hamburger" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><dialog id="account-drawer" className="account-drawer" ref={dialog} onCancel={close} onClose={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget){const rect=e.currentTarget.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)close()}}} aria-label="App menu"><div className="drawer-top"><span className="drawer-person"><Icon name="profile"/></span><div><strong>{name}</strong><span>{email}</span></div><button className="drawer-close" aria-label="Close menu" onClick={close}>×</button></div><div className="drawer-main">{rows(MENU_MAIN)}</div><div className="drawer-section"><h2>Support and security</h2>{rows(MENU_SUPPORT)}</div><details className="drawer-tools"><summary>Business tools</summary>{items.filter(([id])=>id!=='Home').map(([id,label])=><button key={id} className="drawer-item" onClick={()=>choose(id)}><Icon name="manual"/><span>{label}</span></button>)}</details><button className="drawer-logout" disabled={busy} onClick={signOut}>{busy?'Logging out...':'Log out'}</button>{error&&<p role="alert" className="menu-feedback">{error}</p>}<footer className="drawer-version">Version {APP_VERSION}</footer></dialog></div>;
}
