import React, {useEffect, useState} from "react";
import {firebaseReady} from "./firebase";
import {authError,initAuthPersistence,loginEmail,loginGoogle,logout,registerEmail,resetPassword,watchAuth} from "./authService";
import TimberReceipt from "./TimberReceipt";
import {SavedReceipts, LevelTool} from "./ReceiptTools";
import {email} from "./validation";

export default function App(){
 const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[authMode,setAuthMode]=useState("login"),[tab,setTab]=useState("Home"),[online,setOnline]=useState(navigator.onLine),[openedReceipt,setOpenedReceipt]=useState(null);
 useEffect(()=>{initAuthPersistence().catch(()=>{});return watchAuth(u=>{setOpenedReceipt(null);setTab("Home");setUser(u);setLoading(false)})},[]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener("online",update);addEventListener("offline",update);return()=>{removeEventListener("online",update);removeEventListener("offline",update)}},[]);
 if(loading)return <div className="splash"><b>SAB TOOLS</b><span>Checking secure session...</span></div>;
 if(!user&&firebaseReady)return <AuthScreen mode={authMode} setMode={setAuthMode} online={online}/>;
 return <div className="app"><header><div><div className="brand">SAB TOOLS</div><div className="tag">Timber CFT and receipts</div></div><div className="headerRight">{user&&<span className="signed-in-account" aria-label="Signed-in account">{user.email||"Signed in"}</span>}<span className={"status "+(online?"on":"off")}>{online?"Online":"Offline"}</span>{user&&<button className="user" onClick={()=>logout()}>Log out</button>}</div></header><main>
 {!firebaseReady&&<p className="hint local-mode-banner">Local mode: Firebase is unavailable. You can create and save receipts on this device.</p>}
 <div hidden={tab!=="Home"}><h1>Your tools</h1><div className="grid"><button className="card" onClick={()=>setTab("Receipt")}><b>Timber receipt / CFT</b><span>Wood measurements and billing</span><small>2304 formula · Receipts · Print / PDF</small></button><button className="card" onClick={()=>setTab("Saved")}><b>Saved receipts</b><span>Open your past receipts</span></button><button className="card" onClick={()=>setTab("Level")}><b>Bubble level</b><span>Check surface tilt with your phone</span></button></div></div>
 <div hidden={tab!=="Receipt"}><TimberReceipt key={user?.uid||"local"} userId={user?.uid||"local"} initialReceipt={openedReceipt?.uid===(user?.uid||"local")?openedReceipt.receipt:null}/></div>
 <div hidden={tab!=="Saved"}><SavedReceipts key={user?.uid||"local"} userId={user?.uid||"local"} active={tab==="Saved"} onOpen={receipt=>{if(!confirm("Open this saved receipt? Current unsaved entries will be replaced."))return;setOpenedReceipt({uid:user?.uid||"local",receipt:{...receipt}});setTab("Receipt")}}/></div><div hidden={tab!=="Level"}><LevelTool active={tab==="Level"}/></div></main><nav style={{gridTemplateColumns:"repeat(4,1fr)"}}><button className={tab==="Home"?"active":""} onClick={()=>setTab("Home")}>Home</button><button className={tab==="Receipt"?"active":""} onClick={()=>setTab("Receipt")}>Receipt / CFT</button><button className={tab==="Saved"?"active":""} onClick={()=>setTab("Saved")}>Saved</button><button className={tab==="Level"?"active":""} onClick={()=>setTab("Level")}>Level</button></nav></div>;
}

function AuthScreen({mode,setMode,online}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[form,setForm]=useState({name:"",email:"",password:""});
 const submit=async e=>{e.preventDefault();setError("");setMessage("");const er=email(form.email);if(!er.ok)return setError(er.error);if(mode!=="reset"&&form.password.length<6)return setError("Password must be at least 6 characters.");setBusy(true);try{if(mode==="signup")await registerEmail(form);else if(mode==="reset"){await resetPassword(form.email);setMessage("Password reset email sent. Check your inbox.");}else await loginEmail(form.email,form.password)}catch(e){setError(authError(e))}finally{setBusy(false)}};
 return <div className="authPage"><div className="authCard"><div className="brand dark">SAB TOOLS</div><p>Smart Tools for Carpenters & Furniture Workers</p>{!firebaseReady&&<div className="error">Cloud saving is unavailable because Firebase is not configured for this deployment.</div>}{!online&&<div className="error">You are offline. Sign-in requires a connection.</div>}{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}{mode!=="login"&&mode!=="reset"&&<label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>}<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label>{mode!=="reset"&&<label>Password<input type="password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>}<button className="primary wide" disabled={busy||!online||!firebaseReady} onClick={submit}>{busy?"Please wait...":mode==="signup"?"Create account":mode==="reset"?"Send reset email":"Login"}</button>{mode==="login"&&<button className="google" disabled={busy||!online||!firebaseReady} onClick={async()=>{setError("");setBusy(true);try{await loginGoogle()}catch(e){setError(authError(e))}finally{setBusy(false)}}}>Continue with Google</button>}<div className="authLinks">{mode!=="login"&&<button onClick={()=>setMode("login")}>Back to Login</button>}{mode==="login"&&<><button onClick={()=>setMode("signup")}>Create account</button><button onClick={()=>setMode("reset")}>Forgot password?</button></>}</div></div></div>
}
