import{createUserWithEmailAndPassword,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithPopup,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence,updateProfile,sendEmailVerification}from"firebase/auth";
import{auth,googleProvider,firebaseReady}from"./firebase";
import{saveProfile}from"./firestore";
export async function initAuthPersistence(){if(!auth||!firebaseReady)return false;await setPersistence(auth,browserLocalPersistence);return true}
export function watchAuth(cb){return auth?onAuthStateChanged(auth,cb):()=>{}}
export async function registerEmail({name,email,password}){if(!auth)throw new Error("Firebase is not configured.");const cred=await createUserWithEmailAndPassword(auth,email.trim(),password);if(name?.trim())await updateProfile(cred.user,{displayName:name.trim()});try{await sendEmailVerification(cred.user)}catch{}await saveProfile(cred.user.uid,{displayName:cred.user.displayName||name||"",email:cred.user.email||email,emailVerified:cred.user.emailVerified,photoURL:cred.user.photoURL||"",provider:"password"});return cred.user}
export async function loginEmail(email,password){if(!auth)throw new Error("Firebase is not configured.");const cred=await signInWithEmailAndPassword(auth,email.trim(),password);await saveProfile(cred.user.uid,{displayName:cred.user.displayName||"",email:cred.user.email||email,emailVerified:cred.user.emailVerified,photoURL:cred.user.photoURL||"",provider:"password"});return cred.user}
export async function loginGoogle(){if(!auth)throw new Error("Firebase is not configured.");const cred=await signInWithPopup(auth,googleProvider);await saveProfile(cred.user.uid,{displayName:cred.user.displayName||"",email:cred.user.email||"",emailVerified:cred.user.emailVerified,photoURL:cred.user.photoURL||"",provider:"google"});return cred.user}
export async function resetPassword(email){if(!auth)throw new Error("Firebase is not configured.");return sendPasswordResetEmail(auth,email.trim())}
export async function logout(){if(auth)return signOut(auth)}
export const authError=(e)=>{const c=e?.code||"";return({"auth/email-already-in-use":"This email already has an account. Try Login instead.","auth/invalid-email":"Enter a valid email address.","auth/weak-password":"Use a stronger password.","auth/invalid-credential":"Email or password is incorrect.","auth/user-not-found":"No account was found for this email.","auth/wrong-password":"Email or password is incorrect.","auth/too-many-requests":"Too many attempts. Please wait and try again.","auth/popup-closed-by-user":"Google sign-in was cancelled."}[c]||e?.message||"Authentication failed.")};
