import {optimizeCutting} from './cuttingOptimizer.js';
const KEY='sab-tools-cutting-v1';
export const emptyCuttingStore=()=>({version:1,plans:[],offcuts:[],draft:null});
export function readCuttingStore(storage){let text;try{text=storage.getItem(KEY)}catch{throw Error('Cannot read local plans. Browser storage is blocked.')}if(!text)return emptyCuttingStore();let value;try{value=JSON.parse(text)}catch{throw Error('Saved cutting data is unreadable. It has not been overwritten.')}if(value?.version!==1||!Array.isArray(value.plans)||!Array.isArray(value.offcuts)||value.plans.some(p=>!p||typeof p.id!=='string'||!p.input)||value.offcuts.some(o=>!o||typeof o.id!=='string'||!o.material||!Number.isFinite(Number(o.length))||Number(o.length)<=0||!Number.isFinite(Number(o.width))||Number(o.width)<=0))throw Error('Saved cutting data is invalid. It has not been overwritten.');return value}
export function writeCuttingStore(storage,value){try{storage.setItem(KEY,JSON.stringify(value))}catch{throw Error('Could not save on this device. Your plan is still on this screen.')}}
export function saveCuttingPlan(storage,input,result,id){const store=readCuttingStore(storage);const plan={id,project:input.project||'Cutting plan',customer:input.customer||'',input,result,timestamp:new Date().toISOString()};const index=store.plans.findIndex(p=>p.id===id);if(index<0)store.plans.unshift(plan);else store.plans[index]=plan;store.plans=store.plans.slice(0,30);writeCuttingStore(storage,store);return plan}
export function loadCuttingPlan(storage,id){const plan=readCuttingStore(storage).plans.find(p=>p.id===id);if(!plan)throw Error('Saved plan is missing.');return {...plan,result:optimizeCutting(plan.input)}}
// Saving an offcut does not mean the saw has made it. Explicit user review is required.
export function saveCuttingOffcut(storage,offcut,planId){const store=readCuttingStore(storage);const id=`${planId}:${offcut.id}`;if(store.offcuts.some(o=>o.id===id))return false;store.offcuts.push({id,material:offcut.material,thickness:offcut.thickness,length:offcut.w,width:offcut.h,quantity:1,grain:offcut.grain,offcut:true,name:`Offcut ${offcut.sheet}`,sourcePlan:planId});writeCuttingStore(storage,store);return true}
export function removeCuttingOffcut(storage,id){const store=readCuttingStore(storage);store.offcuts=store.offcuts.filter(o=>o.id!==id);writeCuttingStore(storage,store)}
export function saveCuttingDraft(storage,draft){const store=readCuttingStore(storage);store.draft=draft;writeCuttingStore(storage,store)}
