import React,{useEffect,useRef,useState} from 'react';
import {optimizeCutting} from './cuttingOptimizer';
import {readCuttingStore,saveCuttingDraft,saveCuttingPlan,loadCuttingPlan,saveCuttingOffcut,removeCuttingOffcut} from './cuttingStorage';
import './cuttingOptimizer.css';
const id=()=>crypto.randomUUID();
const stock=()=>({id:id(),name:'Sheet',material:'MDF',thickness:'18',length:'2440',width:'1220',quantity:'1',grain:'Any',offcut:false});
const part=()=>({id:id(),name:'',material:'MDF',thickness:'18',length:'',width:'',quantity:'1',grain:'Any',rotate:true});
const initial=()=>({project:'',customer:'',kerf:'3',trim:'0',stocks:[stock()],parts:[part()]});
const area=n=>(n/1e6).toFixed(3)+' m²';
const size=(a,b)=>`${Number(a).toFixed(1).replace(/\.0$/,'')} × ${Number(b).toFixed(1).replace(/\.0$/,'')} mm`;
const safety='Verify dimensions, grain direction, material condition, blade setup and cutting sequence before cutting.';
function Input({label,value,onChange,type='number'}){return <label>{label}<input type={type} maxLength={type==='text'?120:undefined} inputMode={type==='number'?'decimal':undefined} step="any" min="0" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Grain({value,onChange}){return <label>Grain<select aria-label="Grain" value={value} onChange={e=>onChange(e.target.value)}>{['Any','Horizontal','Vertical','Locked'].map(g=><option key={g}>{g}</option>)}</select></label>}
export function CuttingDiagram({sheet,kerf,highlight}){
 const W=sheet.length,H=sheet.width,font=Math.min(W,H)*.027;
 return <svg className="cut-diagram" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Sheet ${sheet.sheet}: ${sheet.placements.length} parts, ${size(W,H)}`}>
 <rect width={W} height={H} fill="#e0d9c9" stroke="#5d735f" strokeWidth={Math.max(W,H)*.002}/>
 {sheet.free.map((r,i)=><g key={i}><rect x={r.x} y={r.y} width={r.w} height={r.h} fill="#f7f4eb" stroke="#a9b7a6" strokeDasharray={`${W*.008} ${W*.004}`} strokeWidth={W*.0015}/>{r.w>W*.15&&r.h>H*.1&&<text x={r.x+r.w/2} y={r.y+r.h/2} textAnchor="middle" fontSize={font*.8} fill="#68745d">{size(r.w,r.h)}</text>}</g>)}
 {sheet.placements.map(p=><g key={p.instanceId}><title>{p.name} #{p.instance}: {size(p.length,p.width)}{p.rotated?' (rotated)':''}</title><rect x={p.x} y={p.y} width={p.w} height={p.h} fill="#c7dacb" stroke="#397365" strokeWidth={W*.002}/>{p.w>font*3&&p.h>font*2?<text x={p.x+p.w/2} y={p.y+p.h/2} textAnchor="middle" fontSize={Math.min(font,p.w/Math.max(6,p.name.length)*1.35)} fill="#263e30"><tspan x={p.x+p.w/2}>{p.name.slice(0,26)} #{p.instance}</tspan><tspan x={p.x+p.w/2} dy={font*1.3}>{size(p.length,p.width)}{p.rotated?' ↻':''}</tspan></text>:<text x={p.x+p.w/2} y={p.y+p.h/2} fontSize={font*.6} textAnchor="middle">#{p.instance}</text>}</g>)}
 {highlight&&<line x1={highlight.x} y1={highlight.y} x2={highlight.axis==='vertical'?highlight.x:highlight.x+highlight.span} y2={highlight.axis==='vertical'?highlight.y+highlight.span:highlight.y} stroke="#ba512d" strokeWidth={Math.max(kerf,W*.006)}/>}
 </svg>
}
export default function CuttingOptimizer({onBack}){
 const [form,setForm]=useState(()=>{try{const draft=readCuttingStore(localStorage).draft;return draft&&Array.isArray(draft.stocks)&&draft.stocks.length&&Array.isArray(draft.parts)&&draft.parts.length?draft:initial()}catch{return initial()}}),[result,setResult]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[planId,setPlanId]=useState(id),[saved,setSaved]=useState([]),[offcuts,setOffcuts]=useState([]),[workshop,setWorkshop]=useState(false),[step,setStep]=useState(0);
 const edit=useRef(0),timer=useRef(null),worker=useRef(null);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const refresh=()=>{try{const s=readCuttingStore(localStorage);setSaved(s.plans);setOffcuts(s.offcuts)}catch(e){setError(e.message)}};
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>{try{saveCuttingDraft(localStorage,form)}catch(e){setError(e.message)}},350);return()=>clearTimeout(timer.current)},[form]);
 const change=next=>{edit.current++;setForm(next);setResult(null);setPlanId(id());setError('');setNotice('')};
 const field=(key,value)=>change({...form,[key]:value});
 const row=(group,key,prop,value)=>change({...form,[group]:form[group].map(r=>r.id===key?{...r,[prop]:value}:r)});
 const optimize=()=>{setBusy(true);setError('');setNotice('');const revision=edit.current;const available={...form,stocks:[...form.stocks,...offcuts.filter(o=>!form.stocks.some(s=>s.id===o.id))]};const finish=r=>{if(revision===edit.current){setResult(r);setStep(0);requestAnimationFrame(()=>document.querySelector('.cut-plan')?.scrollIntoView({block:'start'}))}setBusy(false);worker.current?.terminate();worker.current=null};
 try{worker.current?.terminate();worker.current=new Worker(new URL('./cuttingWorker.js',import.meta.url),{type:'module'});worker.current.onmessage=e=>{if(e.data.error){setError(e.data.error);setBusy(false);worker.current?.terminate();worker.current=null}else finish(e.data.result)};worker.current.onerror=()=>{setError('Optimizer could not start. Reload the app and try again.');setBusy(false);worker.current?.terminate();worker.current=null};worker.current.postMessage(available)}catch{setTimeout(()=>{try{finish(optimizeCutting(available))}catch(e){setError(e.message);setBusy(false)}},30)}
 };
 const save=()=>{try{saveCuttingPlan(localStorage,result.input,result,planId);setNotice('Plan saved on this device.');refresh()}catch(e){setError(e.message)}};
 const load=p=>{try{const plan=loadCuttingPlan(localStorage,p.id);edit.current++;setForm(plan.input);setResult(plan.result);setPlanId(p.id);setStep(0);setError('');setNotice('Saved plan opened. Stock availability must be checked again.')}catch(e){setError(e.message)}};
 const usedOffcuts=()=>result?.sheets.filter(s=>s.offcut&&offcuts.some(o=>o.id===s.stockId))||[];
 if(workshop&&result){const cut=result.cuts[step],sheet=cut&&result.sheets[cut.sheet-1];return <section className="cutting-tool workshop"><button onClick={()=>setWorkshop(false)}>‹ Cutting plan</button><h1>Workshop mode</h1><p className="cut-safety">{safety}</p>{cut?<><p>CUT {step+1} / {result.cuts.length} · SHEET {cut.sheet}</p><h2>{cut.partName}</h2><strong className="cut-distance">{Number(cut.distance.toFixed(3))} mm</strong><p>{cut.axis==='vertical'?'Measure from the left edge of this section.':'Measure from the top edge of this section.'} Blade loss starts after this distance. {cut.trim?`Keep the ${cut.keep} side.`:'Keep the top/left piece; the other side is remainder.'}</p><p>Section at ({cut.region.x}, {cut.region.y}) mm · {size(cut.region.w,cut.region.h)}</p><CuttingDiagram sheet={sheet} kerf={result.input.kerf} highlight={cut}/><div className="workshop-nav"><button disabled={step===0} onClick={()=>setStep(step-1)}>Previous</button><button disabled={step===result.cuts.length-1} onClick={()=>setStep(step+1)}>Next</button></div></>:<p>No cuts required. The parts match the stock exactly.</p>}</section>}
 return <section className="cutting-tool"><div className="cut-editor" hidden={Boolean(result)}><button className="wood-back" onClick={onBack}>‹ Your tools</button><h1>Smart cutting optimizer</h1><p className="cut-note">Sheets, boards and offcuts · all dimensions in mm</p>
 <div className="cut-card cut-fields"><Input label="Project name" type="text" value={form.project} onChange={v=>field('project',v)}/><Input label="Customer (optional)" type="text" value={form.customer} onChange={v=>field('customer',v)}/></div>
 <h2>Stock & material</h2>{form.stocks.map((s,i)=><div className="cut-card" key={s.id}><div className="cut-card-head"><b>{s.offcut?'Offcut':'Stock'} {i+1}</b><button disabled={form.stocks.length===1} onClick={()=>field('stocks',form.stocks.filter(r=>r.id!==s.id))}>Remove</button></div><div className="cut-fields"><Input label="Material" type="text" value={s.material} onChange={v=>row('stocks',s.id,'material',v)}/><Input label="Thickness (mm)" value={s.thickness} onChange={v=>row('stocks',s.id,'thickness',v)}/><Input label="Length (mm)" value={s.length} onChange={v=>row('stocks',s.id,'length',v)}/><Input label="Width (mm)" value={s.width} onChange={v=>row('stocks',s.id,'width',v)}/><Input label="Available quantity" value={s.quantity} onChange={v=>row('stocks',s.id,'quantity',v)}/><Grain value={s.grain} onChange={v=>row('stocks',s.id,'grain',v)}/></div><label className="cut-check"><input type="checkbox" checked={s.offcut} onChange={e=>row('stocks',s.id,'offcut',e.target.checked)}/>Existing offcut (use first)</label></div>)}<button className="cut-action" onClick={()=>field('stocks',[...form.stocks,stock()])}>+ Add material / stock</button>
 {offcuts.length>0&&<details className="cut-card"><summary>Saved offcuts ({offcuts.length})</summary><p className="cut-note">Saved offcuts are checked automatically. Check the physical stock first. Saving or optimizing does not consume inventory.</p>{offcuts.map(o=><div className="cut-stock-row" key={o.id}><span>{size(o.length,o.width)} · {o.material} · {o.thickness} mm</span><button disabled={form.stocks.some(s=>s.id===o.id)} onClick={()=>field('stocks',[...form.stocks,{...o,quantity:'1'}])}>Use</button><button onClick={()=>{if(confirm('Remove this offcut from local stock?'))try{removeCuttingOffcut(localStorage,o.id);refresh()}catch(e){setError(e.message)}}}>Remove</button></div>)}</details>}
 <h2>Parts</h2>{form.parts.map((p,i)=><div className="cut-card" key={p.id}><div className="cut-card-head"><b>Part {i+1}</b><button disabled={form.parts.length===1} onClick={()=>field('parts',form.parts.filter(r=>r.id!==p.id))}>Remove</button></div><div className="cut-fields"><Input label="Part name" type="text" value={p.name} onChange={v=>row('parts',p.id,'name',v)}/><Input label="Material" type="text" value={p.material} onChange={v=>row('parts',p.id,'material',v)}/><Input label="Length (mm)" value={p.length} onChange={v=>row('parts',p.id,'length',v)}/><Input label="Width (mm)" value={p.width} onChange={v=>row('parts',p.id,'width',v)}/><Input label="Quantity" value={p.quantity} onChange={v=>row('parts',p.id,'quantity',v)}/><Input label="Thickness (mm)" value={p.thickness} onChange={v=>row('parts',p.id,'thickness',v)}/><Grain value={p.grain} onChange={v=>row('parts',p.id,'grain',v)}/></div><label className="cut-check"><input type="checkbox" checked={p.rotate} onChange={e=>row('parts',p.id,'rotate',e.target.checked)}/>Allow 90° rotation</label></div>)}<button className="cut-action" onClick={()=>{const p=part(),last=form.parts.at(-1);field('parts',[...form.parts,{...p,material:last.material,thickness:last.thickness}])}}>+ Add part</button>
 <div className="cut-card cut-fields"><Input label="Saw kerf (mm)" value={form.kerf} onChange={v=>field('kerf',v)}/><Input label="Edge trim, each side (mm)" value={form.trim} onChange={v=>field('trim',v)}/></div><p className="cut-note">Trim includes blade loss. Horizontal/vertical grain follows the diagram axes; match stock and parts. Only Any grain with rotation allowed can rotate. Offcuts at least 100 × 100 mm are listed as reusable.</p><div className="cut-optimize"><button disabled={busy} onClick={optimize}>{busy?'Optimizing...':'Optimize cutting'}</button></div>
 {saved.length>0&&<details className="cut-card"><summary>Saved plans ({saved.length})</summary>{saved.map(p=><button className="cut-saved" key={p.id} onClick={()=>load(p)}>{p.project} · {new Date(p.timestamp).toLocaleDateString()}<small>{p.customer} · Open plan</small></button>)}</details>}</div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {result&&<div className="cut-plan"><button className="cut-no-print" onClick={()=>setResult(null)}>‹ Cutting list</button><h1>Optimized cutting plan</h1><div className="cut-print-heading"><b>SAB TOOLS</b><h2>{form.project||'Cutting plan'}</h2><p>{form.customer}</p></div><p>Kerf {result.input.kerf} mm · Trim {result.input.trim} mm per edge</p><p className="cut-safety">{safety}</p><p className="cut-note">Six deterministic guillotine layouts compared. This is a planning estimate, not a guaranteed minimum.</p><div className="cut-stats">{[['Stock pieces',result.summary.sheets],['New sheets / boards',result.summary.newSheets],['Parts placed',result.summary.placed],['Material used',result.summary.usedPercent.toFixed(1)+'%'],['Unused (includes offcuts)',result.summary.wastePercent.toFixed(1)+'%'],['Reusable offcuts',result.offcuts.length],['Total area',area(result.summary.totalArea)],['Used area',area(result.summary.usedArea)],['Unused area',area(result.summary.wasteArea)],['Discard / blade loss',area(result.summary.discardArea)],['Reusable area',area(result.summary.reusableArea)],['Total cuts',result.summary.totalCuts]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>
 <div className="cut-result-actions"><button onClick={save}>Save plan</button><button onClick={()=>{setStep(0);setWorkshop(true);window.scrollTo(0,0)}}>Workshop mode</button><button onClick={()=>window.print()}>Print plan / PDF</button><button onClick={()=>setResult(null)}>Edit cutting list</button></div>
 {result.unplaced.length>0&&<div className="error"><h2>Parts not placed ({result.unplaced.length})</h2>{result.unplaced.map(p=><p key={p.instanceId}>{p.name} #{p.instance} · {size(p.length,p.width)} · {p.reason}</p>)}</div>}
 <details className="cut-card cut-list" open><summary>Cut list</summary>{result.input.parts.map(p=><p key={p.id}>{p.name} · {size(p.length,p.width)} × {p.quantity} · {p.material} {p.thickness} mm · Grain: {p.grain} · Rotate: {p.rotate?'Yes':'No'}</p>)}</details>
 {result.sheets.map(s=><article className="cut-sheet cut-card" key={s.key}><h2>{s.offcut?'Offcut':'Sheet'} {s.sheet} · {s.material}</h2><p>{size(s.length,s.width)} · {s.thickness} mm · Grain: {s.grain}</p><CuttingDiagram sheet={s} kerf={result.input.kerf}/><p className="cut-note">Green: parts · Pale: leftovers · Grey: trim / blade loss. ↻ rotated. Small parts: see numbered list below.</p>{s.placements.map(p=><p className="cut-part-key" key={p.instanceId}>{p.name} #{p.instance} · {size(p.length,p.width)} · at ({p.x}, {p.y}) mm{p.rotated?' · rotated':''}</p>)}</article>)}
 <div className="cut-card"><h2>Cut sequence</h2><p className="cut-note">Distances start at the section edge, not always the sheet edge. Kerf starts after the marked line. Left/top is retained unless a trim step says otherwise.</p>{result.cuts.map(c=><p key={c.number}><b>Cut {c.number} · Sheet {c.sheet}</b> · {c.partName}<br/>{c.axis} · {Number(c.distance.toFixed(3))} mm from {c.axis==='vertical'?'left':'top'} of section ({c.region.x}, {c.region.y}) · {size(c.region.w,c.region.h)}{c.trim?` · keep ${c.keep}`:''}</p>)}</div>
 <div className="cut-card"><h2>Reusable offcuts</h2><p className="cut-note">Save only after cutting and measuring. Plans do not reserve or consume stock.</p>{result.offcuts.length?result.offcuts.map(o=><div className="cut-stock-row" key={o.id}><span>Sheet {o.sheet} · {size(o.w,o.h)}<small>{o.material} · {o.thickness} mm · ({o.x}, {o.y})</small></span><button onClick={()=>{if(!confirm('Has this offcut been cut and measured? Save it as available local stock?'))return;try{setNotice(saveCuttingOffcut(localStorage,o,planId)?'Offcut saved to local stock.':'This offcut is already saved.');refresh()}catch(e){setError(e.message)}}}>Save to stock</button></div>):<p>No reusable offcuts of at least 100 × 100 mm.</p>}
 {usedOffcuts().length>0&&<button onClick={()=>{if(confirm('Have you used these saved offcuts? Remove them from available stock?'))try{for(const s of usedOffcuts())removeCuttingOffcut(localStorage,s.stockId);refresh();setNotice('Used offcuts removed from stock.')}catch(e){setError(e.message)}}}>Mark used offcuts consumed</button>}</div></div>}
 </section>
}
