import React,{useState} from 'react';
import {APP_VERSION,APP_URL,shareApp} from './appMenu';
import StoreProfile from './StoreProfile';
const titles={Help:'Help',SaveInvoice:'Save invoice',Profile:'Profile',Language:'Select your language',Manual:'User manual',Share:'Share App',Rate:'Rate this app',Privacy:'Privacy policy',Bug:'Bug report'};
export default function MenuPage({page,user,onSelect}) {
 const [message,setMessage]=useState('');
 if(page==='Profile')return <StoreProfile key={user?.uid||'local'} user={user} onBack={()=>onSelect('Home')}/>;
 return <section className="menu-page"><button className="wood-back" onClick={()=>onSelect('Home')}>‹ &nbsp; Home</button><h1>{titles[page]}</h1><div className="menu-page-card">
 {page==='Help'&&<><h2>What do you need?</h2><button className="menu-action" onClick={()=>onSelect('Receipt')}>Make a timber receipt <span>→</span></button><button className="menu-action" onClick={()=>onSelect('Saved')}>Find saved receipts <span>→</span></button><button className="menu-action" onClick={()=>onSelect('Baki')}>Check pending payments <span>→</span></button><button className="menu-action" onClick={()=>onSelect('Manual')}>Read the user manual <span>→</span></button><p>After an update, fully close and reopen the app. Local drafts stay on this browser, so save a copy before clearing site data.</p></>}
 {page==='SaveInvoice'&&<><h2>Save your receipt</h2><p>Open the receipt you are working on, then tap "Save receipt". Confirm whether payment is paid or pending to finish saving.</p><button className="menu-primary" onClick={()=>onSelect('Receipt')}>Open current receipt</button><button className="menu-action" onClick={()=>onSelect('Saved')}>View saved receipts <span>→</span></button><p className="menu-note">PDF: use "Save PDF / print" on the receipt page. A draft is saved on this device only.</p></>}
 {page==='Language'&&<><button className="language-option active" aria-pressed="true"><span>English</span><b>✓</b></button><div className="language-option"><span>Hindi</span><small>Coming soon</small></div><p className="menu-note">The app is currently in English.</p></>}
 {page==='Manual'&&<><h2>Timber receipt</h2><ol><li>Enter customer and wood details.</li><li>Use length in feet and girth in inches. Choose CFT or CBM and enter the rate for that unit.</li><li>Tap "Save receipt", choose paid or pending, then confirm.</li><li>For a PDF, use "Save PDF / print" and your browser's Save as PDF option.</li></ol><h2>Wood calculators</h2><p>Choose the card for your measurement units. Enter the dimensions, whole pieces and rate. The total updates as you type.</p><p>Size wood: length in ft/m; width and thickness in in/cm. Flush door: length and width in ft/m. Round metric: length in m and circumference in cm, using the quarter-girth method.</p><p className="menu-note">Switching calculator units clears the entries. Calculators do not save invoices; use Timber receipt to save one.</p><h2>Business tools</h2><p>Saved receipts, Baki hisab, Customer list and Sale report use your saved receipt records. Drafts stay on the current device.</p></>}
 {page==='Share'&&<><h2>Share the app link</h2><p>Only the website link is shared. Your receipts and account details are not included.</p><button className="menu-primary" onClick={async()=>setMessage(await shareApp())}>Share App</button><a className="menu-url" href={APP_URL}>{APP_URL}</a></>}
 {page==='Rate'&&<><h2>Not on Play Store yet</h2><p>Store ratings are not available for this web app. This option is a placeholder until a Play Store listing exists.</p><button className="menu-primary" disabled>Rating unavailable</button></>}
 {page==='Privacy'&&<><h2>How this app handles data</h2><p>Sign-in uses Firebase Authentication. When signed in, saved receipts are stored in your account's Firestore records. Local-mode receipts, drafts and settings use this browser's storage.</p><p>If you enable a Google Sheet register, receipt details are sent to the configured register. You can stop that sharing in the receipt's register settings.</p><p>Share App sends only the website link. Clearing site data removes local drafts and settings, not a backup of them.</p><p className="menu-note">This is a summary of the current app features, not a statement about every provider's retention or security policy. Do not put passwords or payment-card details into a receipt.</p></>}
 {page==='Bug'&&<><h2>Report a problem</h2><p>Tell the person who shared the app with you what happened. Include:</p><ul><li>The page and steps you tried</li><li>What you expected and what happened</li><li>Your phone/browser and version {APP_VERSION}</li></ul><p className="menu-note">Do not share passwords, account codes or customer details. Hide private information in screenshots. No report is sent automatically.</p><button className="menu-primary" onClick={async()=>{const text=`SAB TOOLS ${APP_VERSION}\nPage:\nSteps:\nExpected:\nWhat happened:\nPhone/browser:`;try{await navigator.clipboard.writeText(text);setMessage('Report template copied. Fill it in and share it yourself.')}catch{setMessage(text)}}}>Copy report template</button></>}
 {message&&<p className="menu-feedback" role="status">{message}</p>}
 </div></section>;
}
