export const finiteNumber=(value,{name="Value",min=0,max=1e9,integer=false,allowZero=false}={})=>{const raw=String(value??"").trim();if(raw==="")return{ok:false,error:`${name} is required.`};const n=Number(raw);if(!Number.isFinite(n)||Number.isNaN(n))return{ok:false,error:`${name} must be a valid number.`};if(integer&&!Number.isInteger(n))return{ok:false,error:`${name} must be a whole number.`};if(allowZero?n<min:n<=min)return{ok:false,error:`${name} must be greater than ${min}.`};if(n>max)return{ok:false,error:`${name} is above the allowed limit.`};return{ok:true,value:n}};
export const required=(v,name)=>String(v??"").trim()?{ok:true,value:String(v).trim()}:{ok:false,error:`${name} is required.`};
export const percent=(v,name="Waste %")=>finiteNumber(v,{name,min:0,max:100,allowZero:true});
export const quantity=(v)=>finiteNumber(v,{name:"Quantity",min:0,max:100000,allowZero:false});
export const rate=(v)=>finiteNumber(v,{name:"Rate",min:0,max:1e9,allowZero:true});
export const email=(v)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||"").trim())?{ok:true,value:String(v).trim()}:{ok:false,error:"Enter a valid email address."};
export const validateDimensions=(fields)=>{const errors={};for(const [key,value] of Object.entries(fields)){const r=finiteNumber(value,{name:key,min:0,max:100000,allowZero:false});if(!r.ok)errors[key]=r.error}return{ok:!Object.keys(errors).length,errors}};
export const validateCalculation=(tool,v)=>{const errors={};const dimensionKeys=["l","w","t","h","frame"];for(const k of dimensionKeys)if(v[k]!==undefined&&v[k]!==""){const r=finiteNumber(v[k],{name:k.toUpperCase(),min:0,max:100000,allowZero:false});if(!r.ok)errors[k]=r.error}if(v.q!==undefined){const r=quantity(v.q);if(!r.ok)errors.q=r.error}if(v.p!==undefined){const r=percent(v.p);if(!r.ok)errors.p=r.error}if(tool==="Window Frame"&&errors.h==null&&errors.w==null&&errors.frame==null&&Number(v.frame)*2>=Math.min(Number(v.h),Number(v.w)))errors.frame="Frame width is too large for the opening.";return{ok:!Object.keys(errors).length,errors}};
export const formatErrors=e=>Object.values(e||{}).join(" ");
