import React,{useState} from 'react';
import {woodCalculation} from './woodCalculations';
import './woodCalculators.css';
import RoundWood from './RoundWood';
const types = {round:{title:'Round wood',art:'logs'},size:{title:'Size wood',art:'planks'},door:{title:'Flush door',art:'door'}};
const image = kind => `${import.meta.env.BASE_URL}icons/wood-${types[kind].art}.svg`;
export function WoodHome({onSelect,onCalculator}) {
 return <section className="wood-home"><h1>Your tools</h1><div className="wood-grid">{[['round','imperial'],['size','imperial'],['round','metric'],['size','metric'],['door','imperial'],['door','metric']].map(([kind,system])=><button key={kind+system} className={'wood-card '+system} onClick={()=>onCalculator(kind,system)} aria-label={`${types[kind].title}, ${system==='metric'?'Meter, centimetre':'Foot, Inch'}`}><span className="wood-unit">{system==='metric'?'Meter, c.m.':'Foot, Inch'}</span><span className="wood-dimension" aria-hidden="true">{system==='metric'?'M':'F'}<sup>{kind==='door'?'2':'3'}</sup></span><img src={image(kind)} alt=""/><b>{types[kind].title}</b></button>)}</div><div className="wood-business"><span>Your business</span><div>{[['Saved','Saved receipts'],['Baki','Baki hisab'],['Customers','Customer list'],['Report','Sale report'],['Level','Bubble level']].map(([id,label])=><button key={id} onClick={()=>onSelect(id)}>{label}</button>)}</div></div></section>;
}
export default function WoodCalculator(props) {
 return props.kind==='round'?<RoundWood userId={props.userId} system={props.initialSystem} onBack={props.onBack}/>:<SingleWoodCalculator {...props}/>;
}
function SingleWoodCalculator({kind,initialSystem,onBack,onReceipt}) {
 const [system,setSystem]=useState(initialSystem),[fields,setFields]=useState({length:'',width:'',thickness:'',girth:'',pieces:'1',rate:''}),[attempted,setAttempted]=useState(false);
 const metric=system==='metric',door=kind==='door',result=woodCalculation(kind,system,fields);
 const unit=door?(metric?'sq m':'sq ft'):(metric?'CBM':'CFT');
 const dimensionUnit=metric?'m':'ft';
 const inputs=kind==='size'?[['length','Length',dimensionUnit],['width','Width',metric?'cm':'in'],['thickness','Thickness',metric?'cm':'in']]:door?[['length','Length',dimensionUnit],['width','Width',dimensionUnit]]:[['length','Length',dimensionUnit],['girth','Girth',metric?'cm':'in']];
 const switchSystem=value=>{if(value===system)return;if(kind==='round'&&value==='imperial'){onReceipt();return;}setSystem(value);setFields({length:'',width:'',thickness:'',girth:'',pieces:'1',rate:''});setAttempted(false)};
 return <section className="wood-calculator"><button className="wood-back" onClick={onBack}>‹ &nbsp; Your tools</button><h1>{types[kind].title}<span className="wood-title-badge">{metric?'M':'F'}<sup>{door?'2':'3'}</sup></span></h1><div className="wood-system" aria-label="Measurement system">{[['imperial','Foot, Inch'],['metric','Meter, c.m.']].map(([value,label])=><button key={value} aria-pressed={system===value} className={system===value?'selected':''} onClick={()=>switchSystem(value)}>{label}</button>)}</div><div className="wood-diagram"><img src={image(kind)} alt=""/><span>{kind==='size'?'L × W × T':door?'L × W':'Length × (girth ÷ 4)²'}</span></div><form className="wood-measure-form" onSubmit={e=>{e.preventDefault();setAttempted(true)}} noValidate><h2>{kind==='size'?'Plank measurements':door?'Door measurements':'Log measurements'}</h2><div className="wood-fields">{[...inputs,['pieces','Pieces','pcs'],['rate',`Rate per ${unit}`,`₹ / ${unit}`]].map(([key,label,suffix])=><label className={key==='rate'?'wood-wide':''} key={key}>{label}<span className="wood-input"><input aria-label={label} type="number" inputMode={key==='pieces'?'numeric':'decimal'} min={key==='rate'?0:0.000001} step={key==='pieces'?1:'any'} value={fields[key]} onChange={e=>{setFields({...fields,[key]:e.target.value});setAttempted(false)}} required/><span>{suffix}</span></span></label>)}</div><button type="submit" className="wood-calculate">Calculate</button></form>{attempted&&!result&&<p className="wood-error" role="alert">Enter positive measurements, whole pieces and a rate of 0 or more.</p>}<div className="wood-result" aria-live="polite"><div><span>{door?'Total area':'Total volume'}</span><strong>{result?result.quantity.toFixed(3):'0.000'} <small>{unit}</small></strong></div><div><span>Total amount</span><strong>{result?result.amount.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}):'₹0'}</strong></div></div>{kind==='round'&&<p className="wood-method">Quarter-girth method · Girth = circumference</p>}</section>;
}
